return {
	Easy = {
		Title = "Easy",
		Rating = 1,

		FancyFont = false,
		Color = Color3.fromRGB(119, 243, 71),
		GlobalAnnouncement = false,
		Emoji = "<:Easy:1301038309509955605>",
	},

	Medium = {
		Title = "Medium",
		Rating = 2,

		FancyFont = false,
		Color = Color3.fromRGB(255, 255, 0),
		GlobalAnnouncement = false,
		Emoji = "<:Medium:1301040372608143401>",
	},

	Hard = {
		Title = "Hard",
		Rating = 3,

		FancyFont = false,
		Color = Color3.fromRGB(255, 124, 0),
		GlobalAnnouncement = false,
		Emoji = "<:Hard:1301040697356582933>",
	},

	Difficult = {
		Title = "Difficult",
		Rating = 4,

		FancyFont = false,
		Color = Color3.fromRGB(255, 0, 0),
		GlobalAnnouncement = false,
		Emoji = "<:Difficult:1301040794169511977>",
	},

	Challenging = {
		Title = "Challenging",
		Rating = 5,

		FancyFont = false,
		Color = Color3.fromRGB(194, 0, 0),
		GlobalAnnouncement = false,
		Emoji = "<:Challenging:1301041033382985789>",
	},

	Intense = {
		Title = "Easy",
		Rating = 6,

		FancyFont = false,
		Color = Color3.fromRGB(25, 34, 45),
		GlobalAnnouncement = false,
		Emoji = "<:Intense:1301041176098508851>",
	},

	Remorseless = {
		Title = "Remorseless",
		Rating = 7,

		FancyFont = false,
		Color = Color3.fromRGB(200, 0, 200),
		GlobalAnnouncement = false,
		Emoji = "<:Remorseless:1301041291215241321>",
	},

	Insane = {
		Title = "Insane",
		Rating = 8,

		FancyFont = false,
		Color = Color3.fromRGB(255, 0, 0),
		GlobalAnnouncement = true,
		Emoji = "<:Insane:1301041430445162528>",
	},

	Extreme = {
		Title = "Extreme",
		Rating = 9,

		FancyFont = false,
		Color = Color3.fromRGB(2, 128, 255),
		GlobalAnnouncement = true,
		Emoji = "<:Extreme:1301041835854004265>",
	},

	Terrifying = {
		Title = "Terrifying",
		Rating = 10,

		FancyFont = false,
		Color = Color3.fromRGB(0, 255, 255),
		GlobalAnnouncement = true,
		Emoji = "<:Terrifying:1301041950010642483>",
	},

	Catastrophic = {
		Title = "Catastrophic",
		Rating = 11,

		FancyFont = true,
		Color = Color3.fromRGB(255, 255, 255),
		GlobalAnnouncement = true,
		Emoji = "<:Catastrophic:1301042083179663362>",
	},

	Horrific = {
		Title = "Horrific",
		Rating = 12,

		FancyFont = true,
		Color = Color3.fromRGB(150, 150, 255),
		GlobalAnnouncement = true,
		Emoji = "<:Horrific:1301042195180163158>",
	},

	Unreal = {
		Title = "Unreal",
		Rating = 13,

		FancyFont = true,
		Color = Color3.fromRGB(75, 0, 255),
		GlobalAnnouncement = true,
		Emoji = "<:Unreal:1301042369550094367>",
	},
}
